const OWNER = "site-owner";
const json = (value, init = {}) => new Response(JSON.stringify(value), { ...init, headers: { "content-type": "application/json", ...(init.headers || {}) } });
const noContent = () => new Response(null, { status: 204 });
const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "America/Los_Angeles" }).format(new Date());

function dateOnly(value) {
  const text = String(value || "").trim();
  if (!text || /^no deadline$/i.test(text)) return null;
  if (/^today$/i.test(text)) return today();
  if (/^\d{4}-\d{2}-\d{2}/.test(text)) return text.slice(0, 10);
  const normalized = text.replace(/\b(\d{1,2})(st|nd|rd|th)\b/gi, "$1");
  const numeric = normalized.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{2}|\d{4})$/);
  if (numeric) {
    const year = numeric[3].length === 2 ? 2000 + Number(numeric[3]) : Number(numeric[3]);
    const candidate = new Date(Date.UTC(year, Number(numeric[1]) - 1, Number(numeric[2])));
    if (candidate.getUTCFullYear() === year && candidate.getUTCMonth() === Number(numeric[1]) - 1 && candidate.getUTCDate() === Number(numeric[2])) return candidate.toISOString().slice(0, 10);
  }
  const parsed = Date.parse(/(?:^|\D)(?:19|20)\d{2}(?:\D|$)/.test(normalized) ? normalized : `${normalized} ${today().slice(0, 4)}`);
  return Number.isNaN(parsed) ? null : new Date(parsed).toISOString().slice(0, 10);
}
function dateLabel(value) {
  const date = dateOnly(value); if (!date) return "No deadline";
  if (date === today()) return "Today";
  return new Date(`${date}T12:00:00Z`).toLocaleDateString("en-US", { month: "short", day: "numeric" });
}
function effort(value) {
  const match = String(value ?? "").replace(/,/g, "").match(/(?:\d+(?:\.\d+)?|\.\d+)/);
  const amount = match ? Number(match[0]) : Number(value);
  return Number.isFinite(amount) && amount > 0 ? amount : 1;
}
function points(hours) { return effort(hours) >= 4 ? 40 : effort(hours) > 1 ? 20 : 10; }
function ann(owner) { return String(owner || "").trim().toLowerCase() === "ann"; }
function task(row) { return { id: row.id, title: row.title, project: row.project, deadline: dateLabel(row.deadline), deadlineKey: dateOnly(row.deadline), owner: row.owner_name, effortHours: Number(row.effort_hours), points: points(row.effort_hours), status: row.status, blocker: row.blocker || undefined, notes: row.notes || "", notesAi: Boolean(row.notes_ai), parentTaskId: row.parent_task_id || undefined, sourceKind: row.source_kind || undefined }; }
function completed(row) { return { id: row.id, sourceTaskId: row.task_id, title: row.title, project: row.project, date: dateLabel(row.completed_at), dateKey: dateOnly(row.completed_at), createdAt: row.completed_at, deadline: dateLabel(row.deadline), deadlineKey: dateOnly(row.deadline), owner: row.owner_name || "Unassigned", effortHours: Number(row.effort_hours), points: Number(row.points), day: new Date(row.completed_at).toLocaleDateString("en-US", { weekday: "short" }) }; }
function score(row) { return { id: row.id, date: dateLabel(row.event_date), dateKey: dateOnly(row.event_date), createdAt: row.created_at, amount: Number(row.amount), cause: row.cause, taskId: row.task_id || undefined, title: row.title || "Task", project: row.project || "Unassigned" }; }
function milestone(row, tasks) { return { id: row.id, name: row.name, date: dateLabel(row.milestone_date), dateKey: row.milestone_date, project: row.project, type: row.type, linkedTaskIds: tasks.filter((entry) => entry.project === row.project && ["active", "blocked"].includes(entry.status)).map((entry) => entry.id) }; }
async function body(request) { return request.json().catch(() => ({})); }
async function all(db, sql, ...values) { return (await db.prepare(sql).bind(...values).all()).results || []; }
async function one(db, sql, ...values) { return db.prepare(sql).bind(...values).first(); }
async function run(db, sql, ...values) { return db.prepare(sql).bind(...values).run(); }
function profile() { return { name: "Ann", email: "" }; }

async function smartsheet(env, path, options = {}) {
  if (!env.SMARTSHEET_ACCESS_TOKEN) throw new Error("Smartsheet is not configured for this Site");
  const response = await fetch(`https://api.smartsheet.com/2.0${path}`, { ...options, headers: { authorization: `Bearer ${env.SMARTSHEET_ACCESS_TOKEN}`, "content-type": "application/json", ...(options.headers || {}) } });
  if (!response.ok) { const detail = await response.json().catch(() => null); throw new Error(`Smartsheet request failed (${response.status})${detail?.message ? `: ${detail.message}` : ""}`); }
  return response.status === 204 ? null : response.json();
}
function cells(row, columns) { const map = new Map((row.cells || []).map((cell) => [cell.columnId, cell.displayValue ?? cell.value ?? ""])); return Object.fromEntries(columns.map((column) => [String(column.title).toLowerCase(), map.get(column.id) || ""])); }
function column(columns, ...names) { return columns.find((entry) => names.some((name) => String(entry.title).trim().toLowerCase() === name.toLowerCase())); }
async function sheet(env) { return smartsheet(env, `/sheets/${encodeURIComponent(env.SMARTSHEET_SHEET_ID)}`); }
async function syncSheet(env) {
  if (!env.SMARTSHEET_ACCESS_TOKEN) return;
  const data = await sheet(env); const columns = data.columns || [];
  if (!column(columns, "task")) throw new Error("Smartsheet sheet is missing the task column");
  for (const row of data.rows || []) {
    const values = cells(row, columns); const title = String(values.task || "").trim(); if (!title) continue;
    const existing = await one(env.DB, "SELECT id, status FROM tasks WHERE owner_id=? AND source_kind='smartsheet' AND source_id=?", OWNER, String(row.id));
    const taskId = existing?.id || id(); const status = /^(done|complete|completed)$/i.test(String(values.status || "")) ? "completed" : "active"; const timestamp = now();
    await run(env.DB, `INSERT INTO tasks (id,owner_id,title,project,deadline,owner_name,effort_hours,status,source_kind,source_id,created_at,updated_at)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(owner_id,source_kind,source_id) DO UPDATE SET title=excluded.title,project=excluded.project,deadline=excluded.deadline,owner_name=excluded.owner_name,effort_hours=excluded.effort_hours,status=CASE WHEN tasks.status='completed' THEN tasks.status ELSE excluded.status END,updated_at=excluded.updated_at`, taskId, OWNER, title, String(values.category || "Unassigned"), dateOnly(values["due date"]), String(values.owner || "Unassigned"), effort(values["loe (in hours)"] ?? values.loe), status, "smartsheet", String(row.id), timestamp, timestamp);
    if (!existing) await run(env.DB, "INSERT INTO score_events (id,owner_id,event_date,amount,cause,task_id,created_at) VALUES (?,?,?,?,?,?,?)", id(), OWNER, today(), 1, "task added", taskId, timestamp);
  }
}
async function addSheetRow(env, item) {
  if (!env.SMARTSHEET_ACCESS_TOKEN) return null;
  const data = await sheet(env); const columns = data.columns || [];
  const fields = [[column(columns, "task"), item.title], [column(columns, "category"), item.project || "Unassigned"], [column(columns, "due date"), dateOnly(item.deadline)], [column(columns, "owner"), item.owner || "Unassigned"], [column(columns, "loe", "loe (in hours)"), effort(item.effortHours)], [column(columns, "status"), env.SMARTSHEET_APPROVED_STATUS || "To do"]];
  const payload = fields.flatMap(([field, value]) => field && value !== null && value !== "" ? [{ columnId: field.id, value }] : []);
  const result = await smartsheet(env, `/sheets/${encodeURIComponent(env.SMARTSHEET_SHEET_ID)}/rows`, { method: "POST", body: JSON.stringify([{ toTop: true, cells: payload }]) });
  return result?.result?.[0]?.id ? String(result.result[0].id) : null;
}
async function updateSheet(env, sourceId, fields) {
  if (!env.SMARTSHEET_ACCESS_TOKEN || !sourceId) return;
  const data = await sheet(env); const columns = data.columns || []; const payload = Object.entries(fields).flatMap(([name, value]) => { const field = column(columns, ...(name === "effort" ? ["loe", "loe (in hours)"] : [name])); return field ? [{ columnId: field.id, value }] : []; });
  if (!payload.length) return;
  await smartsheet(env, `/sheets/${encodeURIComponent(env.SMARTSHEET_SHEET_ID)}/rows`, { method: "PUT", body: JSON.stringify([{ id: /^\d+$/.test(String(sourceId)) ? Number(sourceId) : sourceId, cells: payload }]) });
}

const extractionSchema = { type: "object", additionalProperties: false, properties: { items: { type: "array", items: { type: "object", additionalProperties: false, properties: { type: { type: "string", enum: ["TASK", "MILESTONE"] }, title: { type: "string" }, owner: { type: "string" }, project: { type: "string" }, deadline: { type: "string" }, effortHours: { type: "number" }, evidence: { type: "string" } }, required: ["type", "title", "owner", "project", "deadline", "effortHours", "evidence"] } } }, required: ["items"] };
async function extract(env, source) {
  if (!env.OPENAI_API_KEY) throw new Error("OpenAI extraction is not configured for this Site");
  const projects = Array.isArray(source.projectOptions) ? source.projectOptions.map((project) => String(project).trim()).filter(Boolean).slice(0, 100) : [];
  const instruction = `Read the complete source. Inspect headings, paragraphs, tables, lists, dates, owners, dependencies, and milestone language. Extract every distinct actionable task and meaningful milestone or deadline. Do not invent facts or duplicate items. Use empty strings for unknown owner or deadline, 0 for unknown effortHours, concise titles, and a short supporting evidence phrase. ${projects.length ? `Project is a closed-list field. Use only one exact known project when supported; otherwise return an empty string. Known projects: ${projects.map(JSON.stringify).join(", ")}.` : "Return an empty project string unless the source explicitly names one."}`;
  const content = source.dataUrl ? [{ type: "input_text", text: `Source: ${source.label}\nText: ${source.content || "(Inspect uploaded file.)"}` }, ...(source.mimeType?.startsWith("image/") ? [{ type: "input_image", image_url: source.dataUrl, detail: "high" }] : [{ type: "input_file", filename: source.fileName || "uploaded-file", file_data: source.dataUrl }])] : `Source: ${source.label}\n${source.content || ""}`;
  const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { authorization: `Bearer ${env.OPENAI_API_KEY}`, "content-type": "application/json" }, body: JSON.stringify({ model: env.OPENAI_MODEL || "gpt-5.4-mini", store: false, reasoning: { effort: "medium" }, instructions: instruction, input: source.dataUrl ? [{ role: "user", content }] : content, text: { format: { type: "json_schema", name: "work_items", strict: true, schema: extractionSchema } } }) });
  if (!response.ok) { const error = await response.json().catch(() => ({})); throw new Error(error?.error?.message || "OpenAI extraction failed"); }
  const data = await response.json(); const parsed = JSON.parse(data.output_text || "{\"items\":[]}"); return Array.isArray(parsed.items) ? parsed.items.slice(0, 40) : [];
}
async function liveState(env) {
  const [taskRows, completedRows, scoreRows, sources, projects, milestoneRows] = await Promise.all([
    all(env.DB, "SELECT * FROM tasks WHERE owner_id=? AND status IN ('active','blocked') ORDER BY deadline IS NULL, deadline, created_at DESC", OWNER),
    all(env.DB, "SELECT c.*,t.deadline,t.owner_name FROM completed_tasks c LEFT JOIN tasks t ON t.id=c.task_id WHERE c.owner_id=? ORDER BY c.completed_at DESC", OWNER),
    all(env.DB, "SELECT e.*,t.title,t.project FROM score_events e LEFT JOIN tasks t ON t.id=e.task_id WHERE e.owner_id=? ORDER BY e.event_date DESC,e.created_at DESC", OWNER),
    all(env.DB, "SELECT * FROM source_items WHERE owner_id=? AND status='unreviewed' ORDER BY created_at DESC", OWNER),
    all(env.DB, "SELECT * FROM projects WHERE owner_id=? ORDER BY status,name", OWNER),
    all(env.DB, "SELECT * FROM milestones WHERE owner_id=? ORDER BY milestone_date,created_at", OWNER),
  ]);
  const queue = sources.flatMap((source) => { const payload = JSON.parse(source.payload || "{}"); const approved = new Set(payload.approvedIndexes || []); const dismissed = new Set(payload.dismissedIndexes || []); return (payload.extractedItems || []).flatMap((item, index) => { if (approved.has(index) || dismissed.has(index)) return []; const milestoneItem = item.type === "MILESTONE"; const missing = (milestoneItem ? [!item.project && "project", !item.deadline && "date"] : [!item.project && "project", !item.owner && "owner", !item.deadline && "deadline"]).filter(Boolean); return [{ id: `${source.id}:${index}`, sourceItemId: source.id, extractedIndex: index, type: missing.length ? "unclear" : "draft", itemKind: milestoneItem ? "MILESTONE" : "TASK", source: source.source, sourceKind: "file", title: item.title, project: item.project || "", owner: item.owner || "", deadline: dateLabel(item.deadline), deadlineKey: dateOnly(item.deadline), effortHours: effort(item.effortHours), notes: item.evidence || "", notesAi: Boolean(item.evidence), badge: "AI drafted", detail: milestoneItem ? `Milestone · ${dateLabel(item.deadline)}` : `Task · ${item.owner || "Owner unclear"} · ${dateLabel(item.deadline)}`, missing }]; }); });
  return { profile: profile(), tasks: taskRows.map(task), completed: completedRows.map(completed), scoreEvents: scoreRows.map(score), projects: projects.map((row) => ({ id: row.id, name: row.name, status: row.status })), milestones: milestoneRows.map((row) => milestone(row, taskRows)), queue, exceptions: [] };
}
function route(pathname, pattern) { const match = pathname.match(pattern); return match ? match.slice(1).map(decodeURIComponent) : null; }
async function api(request, env) {
  const url = new URL(request.url); const { pathname } = url;
  if (request.method === "GET" && pathname === "/api/health") return json({ ok: true, hosted: true, openAiConfigured: Boolean(env.OPENAI_API_KEY), smartsheetConfigured: Boolean(env.SMARTSHEET_ACCESS_TOKEN), databaseConfigured: Boolean(env.DB) });
  if (request.method === "GET" && pathname === "/api/state") return json(await liveState(env));
  if (request.method === "POST" && pathname === "/api/sync") {
    await syncSheet(env);
    return json(await liveState(env));
  }
  if (request.method === "POST" && pathname === "/api/projects") { const data = await body(request); const name = String(data.name || "").trim(); if (!name) return json({ error: "Project name is required" }, { status: 400 }); const timestamp = now(); const projectId = id(); await run(env.DB, "INSERT INTO projects(id,owner_id,name,status,created_at,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(owner_id,name) DO UPDATE SET status='active',updated_at=excluded.updated_at", projectId, OWNER, name, "active", timestamp, timestamp); return json(await one(env.DB, "SELECT id,name,status FROM projects WHERE owner_id=? AND name=?", OWNER, name), { status: 201 }); }
  const projectRoute = route(pathname, /^\/api\/projects\/(.+)$/); if (request.method === "PATCH" && projectRoute) { const data = await body(request); const status = data.status === "finished" ? "finished" : "active"; const timestamp = now(); await run(env.DB, "INSERT INTO projects(id,owner_id,name,status,created_at,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(owner_id,name) DO UPDATE SET status=excluded.status,updated_at=excluded.updated_at", id(), OWNER, projectRoute[0], status, timestamp, timestamp); return json(await one(env.DB, "SELECT id,name,status FROM projects WHERE owner_id=? AND name=?", OWNER, projectRoute[0])); }
  if (request.method === "POST" && pathname === "/api/file-extract") { const data = await body(request); const source = { source: `Dropped file · ${data.fileName || "Untitled file"}`, id: id(), label: data.fileName || "Untitled file", fileName: data.fileName, mimeType: data.mimeType, content: data.text || "", dataUrl: data.dataUrl || "", projectOptions: data.projectOptions || [] }; let fileKey = null; if (source.dataUrl && env.UPLOADS) { fileKey = `uploads/${source.id}/${source.fileName || "file"}`; const base64 = source.dataUrl.split(",")[1]; if (base64) await env.UPLOADS.put(fileKey, Uint8Array.from(atob(base64), (char) => char.charCodeAt(0)), { httpMetadata: { contentType: source.mimeType || "application/octet-stream" } }); } const extracted = await extract(env, source); const timestamp = now(); await run(env.DB, "INSERT INTO source_items(id,owner_id,source,source_id,payload,status,file_key,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)", source.id, OWNER, source.source, source.id, JSON.stringify({ label: source.label, extractedItems: extracted }), extracted.length ? "unreviewed" : "processed", fileKey, timestamp, timestamp); const items = extracted.map((item, index) => ({ ...item, id: `${source.id}:${index}`, sourceItemId: source.id, extractedIndex: index, dateKey: dateOnly(item.deadline), dateLabel: dateLabel(item.deadline) })); return json({ sourceItemId: source.id, items, extractedItems: items }); }
  if (request.method === "POST" && pathname === "/api/tasks") { const data = await body(request); const title = String(data.title || "").trim(); const project = String(data.project || "").trim(); if (!title || !project) return json({ error: "Task title and project are required" }, { status: 400 }); const timestamp = now(); const taskId = id(); const hours = effort(data.effortHours); const sourceId = await addSheetRow(env, { title, project, deadline: data.deadlineKey || data.deadline, owner: data.owner || "Unassigned", effortHours: hours }); await run(env.DB, "INSERT INTO tasks(id,owner_id,title,project,deadline,owner_name,effort_hours,status,notes,notes_ai,parent_task_id,source_kind,source_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", taskId, OWNER, title, project, dateOnly(data.deadlineKey || data.deadline), data.owner || "Unassigned", hours, "active", data.notes || "", data.notesAi ? 1 : 0, data.parentTaskId || null, sourceId ? "smartsheet" : null, sourceId, timestamp, timestamp); const eventId = id(); await run(env.DB, "INSERT INTO score_events(id,owner_id,event_date,amount,cause,task_id,created_at) VALUES(?,?,?,?,?,?,?)", eventId, OWNER, today(), 1, "task added", taskId, timestamp); const taskRow = await one(env.DB, "SELECT * FROM tasks WHERE id=?", taskId); const eventRow = await one(env.DB, "SELECT e.*,t.title,t.project FROM score_events e LEFT JOIN tasks t ON t.id=e.task_id WHERE e.id=?", eventId); return json({ task: task(taskRow), scoreEvent: score(eventRow) }, { status: 201 }); }
  const taskRoute = route(pathname, /^\/api\/tasks\/([^/]+)$/); if (request.method === "PATCH" && taskRoute) { const data = await body(request); const current = await one(env.DB, "SELECT * FROM tasks WHERE id=? AND owner_id=? AND status IN ('active','blocked')", taskRoute[0], OWNER); if (!current) return json({ error: "Task not found" }, { status: 404 }); const next = { title: String(data.title || current.title).trim(), project: String(data.project || current.project).trim(), deadline: data.deadline === undefined && data.deadlineKey === undefined ? current.deadline : dateOnly(data.deadlineKey || data.deadline), owner: data.owner || current.owner_name, effortHours: data.effortHours === undefined ? current.effort_hours : effort(data.effortHours) }; if (current.source_kind === "smartsheet") await updateSheet(env, current.source_id, { task: next.title, category: next.project, "due date": next.deadline || "", owner: next.owner, effort: next.effortHours }); await run(env.DB, "UPDATE tasks SET title=?,project=?,deadline=?,owner_name=?,effort_hours=?,notes=?,notes_ai=?,status=?,blocker=?,updated_at=? WHERE id=? AND owner_id=?", next.title, next.project, next.deadline, next.owner, next.effortHours, data.notes ?? current.notes, data.notesAi === undefined ? current.notes_ai : data.notesAi ? 1 : 0, data.status === "blocked" ? "blocked" : "active", data.blocker === undefined ? current.blocker : data.blocker || null, now(), current.id, OWNER); return json(task(await one(env.DB, "SELECT * FROM tasks WHERE id=?", current.id))); }
  const completeRoute = route(pathname, /^\/api\/tasks\/([^/]+)\/complete$/); if (request.method === "POST" && completeRoute) { const current = await one(env.DB, "SELECT * FROM tasks WHERE id=? AND owner_id=? AND status IN ('active','blocked')", completeRoute[0], OWNER); if (!current) return json({ error: "Task not found" }, { status: 404 }); if (current.source_kind === "smartsheet") await updateSheet(env, current.source_id, { status: "Done" }); const doneId = id(); const scorePoints = ann(current.owner_name) ? points(current.effort_hours) : 0; const timestamp = now(); await env.DB.batch([env.DB.prepare("INSERT INTO completed_tasks(id,owner_id,task_id,title,project,completed_at,effort_hours,points) VALUES(?,?,?,?,?,?,?,?)").bind(doneId, OWNER, current.id, current.title, current.project, timestamp, current.effort_hours, scorePoints), env.DB.prepare("UPDATE tasks SET status='completed',updated_at=? WHERE id=?").bind(timestamp, current.id), ...(scorePoints ? [env.DB.prepare("INSERT INTO score_events(id,owner_id,event_date,amount,cause,task_id,created_at) VALUES(?,?,?,?,?,?,?)").bind(id(), OWNER, today(), scorePoints, "completed task", current.id, timestamp)] : [])]); return json(completed({ ...(await one(env.DB, "SELECT * FROM completed_tasks WHERE id=?", doneId)), deadline: current.deadline, owner_name: current.owner_name })); }
  const undoRoute = route(pathname, /^\/api\/completed\/([^/]+)\/undo$/); if (request.method === "POST" && undoRoute) { const row = await one(env.DB, "SELECT c.*,t.source_kind,t.source_id FROM completed_tasks c LEFT JOIN tasks t ON t.id=c.task_id WHERE c.id=? AND c.owner_id=?", undoRoute[0], OWNER); if (!row) return json({ error: "Completed task not found" }, { status: 404 }); if (row.source_kind === "smartsheet") await updateSheet(env, row.source_id, { status: "To do" }); await env.DB.batch([env.DB.prepare("UPDATE tasks SET status='active',updated_at=? WHERE id=?").bind(now(), row.task_id), env.DB.prepare("DELETE FROM score_events WHERE task_id=? AND owner_id=? AND cause='completed task'").bind(row.task_id, OWNER), env.DB.prepare("DELETE FROM completed_tasks WHERE id=?").bind(row.id)]); return noContent(); }
  if (request.method === "POST" && pathname === "/api/milestones") { const data = await body(request); const name = String(data.name || "").trim(); const milestoneDate = dateOnly(data.date || data.deadline); if (!name || !milestoneDate) return json({ error: "A milestone name and date are required" }, { status: 400 }); const milestoneId = id(); const timestamp = now(); await run(env.DB, "INSERT INTO milestones(id,owner_id,name,milestone_date,project,type,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)", milestoneId, OWNER, name, milestoneDate, data.project || "Unassigned", data.type === "Deadline" ? "Deadline" : "Milestone", timestamp, timestamp); const rows = await all(env.DB, "SELECT * FROM tasks WHERE owner_id=? AND status IN ('active','blocked')", OWNER); return json(milestone(await one(env.DB, "SELECT * FROM milestones WHERE id=?", milestoneId), rows), { status: 201 }); }
  const milestoneRoute = route(pathname, /^\/api\/milestones\/([^/]+)$/); if (request.method === "PATCH" && milestoneRoute) { const data = await body(request); const name = String(data.name || "").trim(); const date = dateOnly(data.date || data.deadline); if (!name || !date) return json({ error: "A milestone name and date are required" }, { status: 400 }); await run(env.DB, "UPDATE milestones SET name=?,milestone_date=?,project=?,type=?,updated_at=? WHERE id=? AND owner_id=?", name, date, data.project || "Unassigned", data.type === "Deadline" ? "Deadline" : "Milestone", now(), milestoneRoute[0], OWNER); const rows = await all(env.DB, "SELECT * FROM tasks WHERE owner_id=? AND status IN ('active','blocked')", OWNER); const found = await one(env.DB, "SELECT * FROM milestones WHERE id=?", milestoneRoute[0]); return found ? json(milestone(found, rows)) : json({ error: "Milestone not found" }, { status: 404 }); }
  const approvalRoute = route(pathname, /^\/api\/source-items\/([^/]+)\/approve$/); if (request.method === "POST" && approvalRoute) { const data = await body(request); const source = await one(env.DB, "SELECT * FROM source_items WHERE id=? AND owner_id=?", approvalRoute[0], OWNER); if (!source) return json({ error: "Source item not found" }, { status: 404 }); const payload = JSON.parse(source.payload || "{}"); const index = Number(data.extractedIndex); const item = payload.extractedItems?.[index]; if (!item) return json({ error: "Extracted item not found" }, { status: 400 }); const values = data.values || {}; const itemKind = values.itemKind || item.type; let result; if (itemKind === "MILESTONE") { const name = values.title || item.title; const deadline = values.deadline || item.deadline; const milestoneDate = dateOnly(deadline); if (!name || !milestoneDate) return json({ error: "A milestone name and date are required" }, { status: 400 }); const milestoneId = id(); await run(env.DB, "INSERT INTO milestones(id,owner_id,name,milestone_date,project,type,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)", milestoneId, OWNER, name, milestoneDate, values.project || item.project || "Unassigned", values.milestoneType === "Deadline" ? "Deadline" : "Milestone", now(), now()); result = { kind: "milestone" }; } else { const title = values.title || item.title; const project = values.project || item.project || "Unassigned"; const ownerName = values.owner || item.owner || "Unassigned"; const hours = effort(values.effortHours || item.effortHours); const taskId = id(); const timestamp = now(); const sourceId = await addSheetRow(env, { title, project, deadline: values.deadline || item.deadline, owner: ownerName, effortHours: hours }); await env.DB.batch([env.DB.prepare("INSERT INTO tasks(id,owner_id,title,project,deadline,owner_name,effort_hours,status,notes,notes_ai,source_kind,source_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(taskId, OWNER, title, project, dateOnly(values.deadline || item.deadline), ownerName, hours, "active", values.notes || item.evidence || "", 1, sourceId ? "smartsheet" : "file", sourceId || source.source_id, timestamp, timestamp), env.DB.prepare("INSERT INTO score_events(id,owner_id,event_date,amount,cause,task_id,created_at) VALUES(?,?,?,?,?,?,?)").bind(id(), OWNER, today(), 1, "task added", taskId, timestamp)]); result = { kind: "task" }; } const approvedIndexes = [...new Set([...(payload.approvedIndexes || []), index])]; const status = approvedIndexes.length + (payload.dismissedIndexes || []).length >= (payload.extractedItems || []).length ? "approved" : "unreviewed"; await run(env.DB, "UPDATE source_items SET payload=?,status=?,updated_at=? WHERE id=?", JSON.stringify({ ...payload, approvedIndexes }), status, now(), source.id); return json(result, { status: 201 }); }
  const dismissRoute = route(pathname, /^\/api\/source-items\/([^/]+)\/dismiss$/); if (request.method === "POST" && dismissRoute) { const data = await body(request); const source = await one(env.DB, "SELECT * FROM source_items WHERE id=? AND owner_id=?", dismissRoute[0], OWNER); if (!source) return json({ error: "Source item not found" }, { status: 404 }); const payload = JSON.parse(source.payload || "{}"); const dismissedIndexes = [...new Set([...(payload.dismissedIndexes || []), Number(data.extractedIndex)])]; const status = dismissedIndexes.length + (payload.approvedIndexes || []).length >= (payload.extractedItems || []).length ? "dismissed" : "unreviewed"; await run(env.DB, "UPDATE source_items SET payload=?,status=?,updated_at=? WHERE id=?", JSON.stringify({ ...payload, dismissedIndexes }), status, now(), source.id); return noContent(); }
  return json({ error: "Not found" }, { status: 404 });
}
export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname.startsWith("/api/")) { try { return await api(request, env); } catch (error) { return json({ error: error.message || "Request failed" }, { status: 502 }); } }
    const response = await env.ASSETS.fetch(request); const html = request.headers.get("accept")?.includes("text/html");
    if (response.status !== 404 || !html || !["GET", "HEAD"].includes(request.method)) return response;
    const index = new URL(request.url); index.pathname = "/index.html"; index.search = ""; return env.ASSETS.fetch(new Request(index, request));
  },
};
